#!/usr/bin/env php

require ROOT_DIR . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new InstallerCommand());

$application->run();
