// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ph7-app/Dashboard.tsx": () => import("../components/mockups/ph7-app/Dashboard.tsx"),
  "./components/mockups/ph7-app/Landing.tsx": () => import("../components/mockups/ph7-app/Landing.tsx"),
  "./components/mockups/ph7-app/Profile.tsx": () => import("../components/mockups/ph7-app/Profile.tsx")
};
