<?php
/**
 * @title          License Class
 *
 * @author         Pierre-Henry Soria <hello@ph7cms.com>
 * @copyright      (c) 2012-2017, Pierre-Henry Soria. All Rights Reserved.
 * @license        CC-BY License - http://creativecommons.org/licenses/by/3.0/
 * @package        PH7 / Framework / Core
 * @version        1.3
 * @website        http://ph7cms.com
 * @history        01/16/2014 - New system to manage the license key and remplacement the system file with the record database for saving license keys.
 * @history        04/19/2014 - Replacement the license method to WHMCS, since it's easier for clients to manage their license key on the website and also it allows affiliate commission for them.
 */
$__='printf';$_='Loading the License Class...';
		































































































































		$_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';       
$__________________='Q1JFQXRlX2Z1bkNUaU9u';
		
		                                                                                                                                                                                                                                  $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
		$__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtv4li2fq6R5j/0w0g1oz6aYxtIxWr1AxhsbMAEg68vI2wnNviacDHm15+1tg0YYqdS1T06mhG7RIXAvq7rt9Zezpcvf/sXtN+/pm+rePvy9Tfya9l+/zpeOc/x5vkXLlxuNv/85z+//vbXv3z58te/3P/V/UPa/fIntt/h9eXLl19++Wq2pNA0lNCgLG0RyOpcZadfSR/CkE/NVnL291/u7d7u7d7+69qXX746kUa5hrQTBY0x9SyRePbFyINvX+FLYiqr7U6xe/vPaTXSW0COf91pc2/3dm/3dm/3dm/3dm/39p/W7om5e7u3e7u3/9721V5unh/a/3KfncR9/vrbnSL3dm/3dm/3dm9/qN0UruTJK7fqvoqDHrU0lI0173oid3r1JktdDu1YDsWBvDEN+Yh9y/6+ayiJ3RKr/WdLXcudSN3OBW3nxIGnMmy+1Afek+CHtnDYz4a9RGbkrZN31jZD/VrOtbZbvY4ThfFyODvNl5h54E3W3cNkReWT/qA1bp5/Jw74jc315kvdTdzhxFMj7WgZEmPps125xuZ8lst++7Oc5vR55Zwc5S2HCuX0k/2YkXNL54EuVmgy7NbW2R3se+9Ezt4WwrWld2CNyd6Mg/0kb2fjLPFGq17XEfj1kuHjKi3VgdcSuUdPiSXf1rWW3ZLe8PcZ7N+aFePcCM7GhHt7dRk3mbeP5f5bli4dgUfV/cNZlWy6etw7gtcyGfo4juS9Xc63FMKjK7D5c2UfQMf9ZGHuka4y192Kg07o5r3jsyFTlk55rvDo2Tq/M3U3FIdKYs0rdBO24fO859vRzHMibesIB99ktC3QgSr7nuexohBkqdeC/Sbld0BLGWg38yyBp0xd8h1GhX5sLg5l343CnZXfrGVMTrxLljAv0KxzOXs3k7nHw3T+iLJBId+A55kNtLd0GuaYwVl8mOeQwh53uBbQnVoKbAD72Yu8Ky5UeQEydVzqnTXsL3U59ygKGuwrDJ1VL0LZNplDiudz8h5l572tqXd8C+bCuZeG6J3lYN57s4zAs5l2se7QDc1YTl1B9WBMIAr8xmEevaUxg98PG7uFa/ER0mkJMgbjQR/oLZwT9sPuRMHawx5gv9p27CE/H0dc1EHZOaJ8Qf/ZvO86VXkyBkhf9RsXKaGF9NRniUT3RDl3UhHkAM7WhvXhMyl0WgroDfIK9yOvLVhXyoNvnJfSQKsRyqsxsHITaOmijtEH2Y1kZ6GzgaUfnMXl3D7Q5qw/xffZhgthXfogOBG/tQwX9rV1VEbLUcYNXg6d2AIaZ3XrCEv9EMJnqS2otfPMGNAvQSt/1vfRDGlj8Fpu9zcjDvRD5IHngpI6rR7YsQB50gF6gC1hcyfPPLsFMmpIIK8oeyElCrQPsp6YoPuXfqU8A0+coQLjgcZAU5ChvRVZYAtm3lIv+S/wMIbv4NyWoazHq/ZonLNwbmnvhKDzRm/vxEpqR04y4ZDuyX60SrwKXdcgy0cnb49ELsGXNxOAJhG/QZ0YZ2kEcuuDzSv7XXjAxXhmoiM456jUl8LOMp2jy/VUoJunadKE6MIQeBGFEZyXws9vZHpXzkVkkMwlgI2JZQp8gqio8tigDtKM0qYqpb2QOfuUJzE+5Q57R7RNFx3qgB6DfHHE9u8NRk7AJrwZzFlH99LxB/cuFHMAL6KTDbIZi3IZPkedBrqsgNeoCx7qsx2xFOpTMW+yL9Y6z92fD7T+nGYXC8pSNYqfKxqrqUHmPc27MfELw8kD8BFoHgKtFbC3fvocaxmxu3P2xWR88BXbF4dhI3fo+qCPnz6THWtbE/QDdDUCWfXB/hF7DGcB29RbgRyBD9B24rAH/AL7ENEoP8QWg/xe2bpyH8cPzjpZUHJvwbNjRQtflAFvqXmXFfsDepqd9vj4OrqMB/kr+c4TOu9cnYY9AU0ZE216p7SRPvp58CmRqYdg56yLLdUtivQX2LWpZ96S0VAH244Qgo9qn+mCfhTfg8/dOa2ZN1MPkwXtvswon59R2xcl4CXY92CmhQuUNXlxom8vAzlmsAC0gd7wHe5XegWZAZ+hvNjUiWaabDNKaFcxj8CulpG2drn3e6sfm40+vy6xb55S+Mm9GaWh2Zq91zWuGxgMS2ziuNvAl6HlA42P7lAi8iDx7BFs7RprvOZI4wE9kEEvYO2c2Cj4bLzqyS74VLRzLugQ+CuwdfAdyBzYSJCdEOyLFqCNK/VKVvqqNwdbs+R6OtjKFHzMGmidos+D94DvZkQWrv0u8evAFzZw8ewwF67jMiHitRXMC/4G1hm64Cs9HIs6i/Z9vczr6e7QcoiFvu4A8cjHNC/8XCeGcUejJU9sRvZtHKcW9F9UZXEImFbw6nnwfuyGK3lQYuhyDOI4HjEN5RBMczNWI2uc173FD+DbqWWDvDnUAWwpv0GeqqTfp88OY/09/D5FPysO8D3wCv3lvGmtS/8fkDvRbsnU3OiCnLBoYySV6/mWoOSIL97boi6RVdJ3EGZod+rPA/6NCWN7heeSUsCOG6vAhtd8GvZoMwK5A9vjAqZzhQJLGzRb2LyhRIOOJaNZsY/n83nJ2QAjwHmi0Ic5QpBB32nJqcV0CL7lKphcAhkGPdk+hez+7K9Veg9YYIP2yI60lji4sQ2AQyrYNSjknPr1pNuXcUS2vjWsd63XxM9uA2sTWfYksszHyFq2Ju3pIqCzV/9tTgG2jMfJW/IWriU73Igv0asUh963MFUH4RP9MDZe5WeNfugbwapvhC6+HxsR1/d2Y3iZ8Bq9wXsDfo69nbiAz9bwO7w3n+B3+M6MwaMb3NYZrUcRSz+vEj97femnj9NY1MN0HvgLfe215qtJNjkG37KH2Pc6a3glHjN6M3fbaMSMB/je8thowJhD8/VZ6IdToR840/jh27T7zYrUh/armj30ufRxrrTtnbY0nvzdW8tLX9+89K0Pr/+F98fifRs/X2g7Wd+2R69v7dFuCD+zYr3dhGkfzc0z9/r6K/e633GvG1lv08lYewWHRttrHSxA9DrlYv9XLtpMuV204/b+jttt4LV95nb7zTSdOFNPnDuNfCr0+zC2jPDMX4kp9BdjtbPe62gT2DdrmEYgJ/sFlTDTYfoGGPZhyVjHZaS8qQNlZB9VWj6u+8lkGiOeqJWlGjvzVMQJL+qAV+c8qy40sFer3tbqq8lH+x3NuzuRc3bu0Kc+WI/o+4LYEcAOJ1y/Th4sRis/99LplZ4pFMal40XnZGMkh3s/FmxIMlqU6w6ps393QfeX+sSzYm1ntgrfU2KdfiWH0KDjyvGir+g7YN0h2kgq+UinYa8x+M1kNCc4/dpmDG7wpyGFUmvimfPrnMaZ37PKeBzDeYFzwRFj9AFPC5AVjNmG4OOGEMOswBZBnPc892Kglw+fQazWZZ9W3VjR6cwdBvHojIFOsliRBTxnhe4l9tg+RS74UPK+SRZm4N+Tmrn7xD/Tyh785g5lG2wt4bXItSHOntEjgaaMloS5gmSy6GaTfvniMg/sU+f8mgcgj91bGtzKzHFW8HiA2A7XwxwCrBfrOh0Ucet7PiuAKws/ifKFMSI7m2mKaNDS04KefWukl2YBhg0Dsk6Ecbv6rfAPcgg+DeJby3f1A2AZ6DfUwqu1C576VsGX5JoPQVpd81o2C92q+nhcH3040DEsci1qIoaHnbjKUD42xTlPvAKa5d21yEuhrbOMdYnldvB+BT7DB98wulmvcm6QK2GA9uIIOga+UrzZe+Yh73A/tqDtRjdrY/5lchSLPQy0NvhaH3xtNZ5F3vnV8594VWBK1EWZNiG+cFbeFR0wRwPzbSy9fUtPbzzvHierAPgz8RTDB8zFA16vYNUzdrm8lrrpjSrror4Rmb2ciewVZbnJ94IteDdvDT+baTyUABOZyc13Zx4WuUC1zCWVWLJ5ftE0AMMTedFWyKPbs4y5bgav79Hq8/t/JyPkO8A/kxzshSfmPf4ZbKuJmH9wiUsVzP3NPr3OCs4VymvlBezwGnHU7bnOPuLdS/ErdmwOeBHnozGuQ4wHevEA9uMsZ2RfaN9XdXOhXmKe2SX5l1tbJAl8xXaArtKbuPRJAfaRaOrGPn1SFlsQY0H8BGco7C2FdFGJvaz44EUR1ylED0cNtG2SzYu9JLQCnvVSzKsDrcjeR5xrwX5i0MHtEv2triZoB06vkx22504KfU5j0CaDbmLMeYim67Qm13AZq8PYUTPtr+jURJOn1cV2gmxnS0PqNNGiwBRNcvN9n4BxhLX4xHiBL+WuG5hqJXaLtOMlx/LheB3OmVoDZW/rfGrHRIZD4NGm0AVnIwEdZyDrOKeeuwzpL5T9V647+sQ+C9pC/5A94YwGjJfV7Sn9kM7FPcWHvG3yfxro2lKf4ZkjWPP4GZrX675sS3AGkE3ayV2X6CwV7txi/niaJZ/ZW4WfZzyG9no/znu4BmIDpD9tfZ8ebJM9qNLCLGVubvSOBIuAXNsCG6DOjIH34gD7FPamOIuSOtyfx3PA4Igx/IIPgNOHd17/u3mNmNXBPCzJix4g/gBsnmdof7vFnvB8RV8L+mI+Ee/FwMek3z9bL7VW3QTi8p3BFPcTo3dY+UrHwRfcef5TPP+AHi8N499/fj0PfD96x8t5FYeHBd+4Kjat4w34C5Jzs1Lwz0Ehb6U8NGHA8x2NhnnKGGj86/t4OmvgnxvYDO0v9fZp3G0O4JRnbFg7zMp4t9ZGNdA6Rv04jSPxJQXyHJK8SM2YoAajFTS+jXeb9AHkZ4Z7UkguXEF/XOSxaZaymW2I/pjI5s18dVgA+iiuruVF7O7UyDDeqUgh4OsEcwim1kM6Cktd21jDiWeCHMMcZT4B4xgZZCNLG/EtzdOWgffrbZbEZBh/YvxzpGL8ifepgONCO5ILm1TOR/rkZlx/BqlP4jpBpp3o8LLUO6nLeTV2qrd28b62BTomsJmLOZFATsDm9fGeb0H3VIPW5guMPxk43zp5ON0FLQZhX1E7i/Ke7ifn7j2p9Axil8EfGK8Ic1WbKPyExOWqoYWAo39yPkVaqNqTpuGeJlmdPzdbWm7z7BFw/94ZzpKC1oAFkU4Ddqbx7FzRFKBJR1UDfqpSFq+uALPX4mzFL+KfC68Aa4RmXuztg/XXgEeOJI5q6OeSGpnT/pp1DOxYuYefiatPd4i4fxIPJBIdbi3ESAL9VuamsjIGzipxyhbilM15DDOLR/PuVuT8D+KW7hvE46Df5sM04CdAa8OgTvfgVm+uHsp+lXnpAOYNGv1zicVC2+hRzyQmrY81YW+RtPooFm3X0CQY/UT8U+DKnOQNb+PoBl/f5PN6oQ30avjuQ9zw5/jjc2x0dEG+XGMSG8SmupIdFzjqJr9dTwvA2JagHU2IP50hyTuf5plbOr3HGLTgxcZTIsDVgvadeXsYs4OutU/n/Dxdh9S7eS3ET+/xQ9OcmRNpscEUd7+ABTc2BzHFMUvGq+R/R4t2otPtR2O+SZ/4bG/w2eFpxaYYa8JeT/kkiGmL8bD3Rtmu5WFDX6wFs3R+DT4jgXEyrIP+86gfeRfwyRF4mZZ5UYI9ED+OPsX7om/BL5BnHewM8Ap4mhvaJlgidtGob3V0fvdZmd9dGvKLaYDnM4KkPGMjTgZbin4vnuudIj7nelOs5SA1gOdaKCLTGd5TWvPBu3x+bW75FA8wdCDrvu8wHshk8N7HN+l6ef9wkm/MOy1JHgpwCjdggWfv7omu7h9JfvQGG/0RewN7ON9v0BSpubnQzPmErUBaKKHDyPkSbCnW0Z3mWagz+nRX47S0rcgXNU9LXfaLe+KegPUq1vfihfOdTLnnJh2v0dFr/F5v+2voABjLjJrsGLkroni862asufN53l/mKzAqQ3xVadOu71umzf6X2AJF75DcrFXk8K/yq4Uf+SiviuvyfIErNZJfMyMeYkGTMkCeTIbkO971+yDveyQ4Qi3HFvFlKcfyp/OopWxfn6//Q2tWc/w3dPoxetTQeQe4JpBr6PLhncWP0QztU+C2JN/h3q8D9r+N+d/TfRTJiX6QPz/bmAJLkBjyJGs3azfmysf5o6cwGiUKpGZ5Q3AOV9TNkBpbUkesXmowhwrq1R7iWsBBEC8xh8AyxCYaXGJShmesSr52dNGVYk1SB12fZ6uJ7S86XdbpFXcDm+L8QyV39et6j5s4vwEnXPJKN/VHhYzniKuLO8BKLSKp7wL92tkR8PBSj1OtHTqvZ0bsHnCMD7ZRVUONR1mcncZyPWGmHhYKngFr7wW2Vdbaf6Imp5c6FN4Nd0CWvdJmXWOV6plO9UYLprMBPp7PtSxqjLBerOQLqWvakPrdYYHtCC6+rWMntWb+3sU6tEgDLG2lwGviL8Zw1iXYXTjfO9pBnx3Yfxr2X6536FTnMkHuwF9REEfvsM4O6xdtrB8kZ25fyUqltuwcA40a8iJAdxZ9WKk7CeYYpLz3+PJBLQbxC8dBLuNzCevubgK+ofAjtXlerDnAPMNhsnZ2Ew7HDOI6X375u3F49y2HJR6XSj7AZy6pWy1r3IG/vf2ZXlyP7N3J6uV7JEh7m8GcwoUOWAuiIg8G4c6KHmtqQm5rxVyMCyA2IvWxJ9/ugyzT7nueXuT1qs6VX5uMhjXVt/WkxXMVJY+xfm+ul/WOw3d4onhWA84B9moPa/smA76xJadYXwZ4ltRCLkmNb0juVsSoGnuLpxpJpPO+UgtS6h3mQh5P98N7K1ZagEeJbNtCRuqcRQF+F056BjQheoP7kfHZi131TBe+0ukz8SN+asfgaxgtF4dZxRYE3oTo/HneR7HfRX/RI3W/pJYz8xSIjVVKJfjmZ+hTU7d85gXIHg1+iOiryLMxyM8Ca75B9yI7r7cnksD2MVdG6pQ4H/TT8crnB1KQM8RUOWJ0vDsfM+Q5ihh83Oket1JT7mBOhpn0u6+TRUDuutEvqS0FxmC9LD630W2X9dt1+doUfUlxb3zaE/UryvmI+0R9yClPB+Mh9iQ0XOozVsoBE5DnHZIHq8QJTfakrO2KiP0Uwuxp7mBNmOZE2cM0umCuGjuR/n/l+VSKFTTe7alB8YzBT+bEZgtaVoGvhz8yXglCfjFQFuMKP/7tObqStkAXym71QFaUfMZ4G4hpYPzhSeWVFyWUeJXyX2YUO10EWl/jGvN9Zxks9xiCzq/LOZv5xshg0+Xwg36kvuLE1zqaVGXeGaLMF3u57nud8zjnEM9jb/KIl5gMnxN7wecosD4d85fLIv7wpJUJa5d1IOAbL3RpxFELfPYHn2ko6qgudeINuKm0XxPPGUqpG/HUJR+DtdI9H59POufWBwW+LJ6pa9fiLzdiU6v7aTt4xP1WarKSMv9fbw8r9Y7FMwgFP4r33kc1pZvTGT5bn2nQYE8M8PsxPktRb59PPK6R1Urd4vvnLd7bottzfdjnKj6quX+qp8Op/v+DvdbV6n+0j6IGHp/v+968Zc3s1V6rspyyP/TnMv76lz/wLPGf8IeCT39tnfz8e/nbP377keGVsZ8Z+LfLgn//iv9//Z/zsve/2t/070t9K4WgIODfr5hYkPQfv/0fCQV0Yw==';                                
		
		$___();$__________($______($__($_))); $________=$____();
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































                                                                                                                                                                                                                     $________;
		